### ISSUE TITLE
Version 0.2.1 on maven central?

### ISSUE THREAD

**Issue by tkawachi** [softwaremill/retry#20]
I found retry 0.2.1 is [available on maven central](http://mvnrepository.com/artifact/me.lessis/retry_2.11/0.2.1). Though 0.2.1 tag is not found on this repository. Can we use it?
I prefer maven central to a library specific repository. I'd happy if I can use .jars on maven central.

**Comment by atronchi** [comment]
The retry_2.10/0.2.1 version on maven central depends on odelay-core_2.10/0.1.0, but the .pom and .jar are not present there, so build fails when importing 0.2.1. FWIW I have the same error trying to load retry_2.10/0.2.0.

**Comment by atronchi** [comment]
The .pom and .jar files are present on maven for odelay-core_2.10/0.1.1, so it looks like we would just need to update the dependency reference in https://repo1.maven.org/maven2/me/lessis/retry_2.10/0.2.1/retry_2.10-0.2.1.pom to point to that version, as long as there are no backwards incompatible changes between 0.1.0 and 0.1.1.

**Comment by adamw** [comment]
Done in 0.3.0
