### ISSUE TITLE
0.2.1 on maven central depends on odelay-core 0.1.0 (not on central)

### ISSUE THREAD

**Issue by tkawachi** [softwaremill/retry#23]
[retry 0.2.1](http://search.maven.org/#artifactdetails%7Cme.lessis%7Cretry_2.11%7C0.2.1%7Cjar) depends on odelay-core 0.1.0 which doesn't exist on maven central.
Please release a new version which depends on [odelay-core 0.1.1](http://search.maven.org/#artifactdetails%7Cme.lessis%7Codelay-core_2.11%7C0.1.1%7Cjar) on maven central.

**Comment by adamw** [comment]
Done in 0.3.0
