### ISSUE TITLE
Please publish to maven a scala 2.12 version

### ISSUE THREAD

**Issue by jacobg** [softwaremill/retry#25]

**Comment by adamw** [comment]
@softprops as I've hit the 2.12 problem today as well, maybe you would be interested in somebody else taking over maintenance of the library? We (@softwaremill) would be happy to, of course retaining all credits etc., but possible changing the maven group id to one that we can publish to central.

**Comment by softprops** [comment]
Have been on a holiday but have not had time to give this the love it deserves. GitHub has a transfer ownership option. Would @softwaremill be the account you'd like to maintain it under?

**Comment by adamw** [comment]
@softprops yes. Although I'm not sure if that wouldn't also require `odelay`?

**Comment by softprops** [comment]
I can transfer ownership of that too if you'd like

**Comment by adamw** [comment]
@softprops sure, we'll be happy to take that over & release to central as well!

**Comment by softprops** [comment]
@adamw. I'm getting this error message ”You don’t have the permission to create repositories on softwaremill" I'm assuming because of some personal stuff issue. Can you add me as a collaborator to the org? Another option my be to transfer to your account then you can re transfer as an existing contributor

**Comment by adamw** [comment]
@softprops hm, I'm not sure how that works, maybe you can simply transfer to me and I'll try to sort this out later. I think user->user transfers work without any additional work

**Comment by softprops** [comment]
@adamw ok two inflight transfer invite s sent. One for retry and one for odelay. Enjoy!

**Comment by adamw** [comment]
Thanks! I'll take care of the updates/ releases in the evening or throughout the weekend :)

**Comment by adamw** [comment]
@softprops I made some changes to the build and published to sonatype version 0.3.0. Please check if the attribution etc are ok for you as well as other changes. Thanks!

**Comment by jozic** [comment]
what about https://github.com/softprops/undelay? it also depends on odelay
@adamw do you want to take that as well?

**Comment by adamw** [comment]
@jozic looks small enough, if there would be interest, but I wouldn't want to take over all of of @softprops projects ;)

**Comment by softprops** [comment]
All of these are relatively small at single purpose. I'm happy to transfer ownership to that as well

**Comment by adamw** [comment]
@softprops well I suppose, one more for completeness wouldn't hurt ;) Btw. - are the changes so far ok?

**Comment by mrvisser** [comment]
Did a 2.12 cross-compile end up anywhere?

**Comment by mrvisser** [comment]
Argh, I completely overlooked the `me.lessis` -> `com.softwaremill.retry` change. Sorry for the nag.
