### ISSUE TITLE
The backoff samples examples don't compile

### ISSUE THREAD

**Issue by LukeDefeo** [softwaremill/retry#26]
This code doesn't compile on scala 2.11 library version 0.2.1

```
implicit val ec = ExecutionContext.global
    implicit val success: Success[String] = Success[String](_.isEmpty)
    implicit val format: Formats = DefaultFormats
    implicit val timer = odelay.jdk.JdkTimer.newTimer

    retry.Backoff(4, 1.second) {
      Future {
        ""
      }
    }
```

though this does

```
 val withBackOff: Policy = retry.Backoff(4, 1.second)

    withBackOff {
      Future {
        ""
      }
    }
```

is the readme just out of date? 

Is it ok  to store the Policy as a instance variable and invoke it multiple times with the closure. I think i actually prefer it this way as its more readable but none of the examples seem to work like this

One final bit of feedback is why do you require the user to wrap the operation in a future, couldnt you accept any T and wrap it in a futre internally

**Comment by mkubala** [comment]
Thanks for reporting this issue. 
Indeed, the README is out of date.
