### ISSUE TITLE
Success condition can be a failure 

### ISSUE THREAD

**Issue by grogdotcom** [softwaremill/retry#33]
I have a method that I want to retry that could result in multiple exceptions. Only one of them I want to retry on the other ones I want to consider as a success and throw that exception. 
The Success condition for the Policy is only checked within a `.map` of the future being evaluated so a failed future will always result in a retry. 
Is there a way to only retry on certain failures without having to wrap the content of the futures in a Try or Either?

**Comment by GEverding** [comment]
@grogdotcom did you find a solution to this? I'm trying to do the same thing.

**Comment by grogdotcom** [comment]
No there is no good solution. what I ended up doing was wrapping the future in a Try 
```
def retryOnlyOnSpecificException[A, B <: Throwable: ClassTag](attempts: Int, initialDelayInMillis: Long)(f: () => Future[A])(implicit ctx: ExecutionContext): Future[A] = {
    val success: retry.Success[Try[A]] = retry.Success[Try[A]] { r =>
      r match {
        case Failure(_: B) => false
        case _ => true
      }
    }
    val retryJittered = JitterBackoff(attempts, new FiniteDuration(initialDelayInMillis, TimeUnit.MILLISECONDS))
    retryJittered(f().map(r => Success(r)).recover { case l: Throwable => Failure(l) })(success, ctx).map {
      case Success(r) => r
      case Failure(e) => throw e
    }
  }
```

**Comment by noahlz** [comment]
I also need this, would be nice for it to be built into the library.

**Comment by noahlz** [comment]
I'm not sure if a library change is needed, I just defined an inline Success that treated exceptions I didn't want to retry as "success" - wrapped in a scala.util.Try

```
  val failFastCertainErrors = retry.Success[Try[Any]] =
    retry.Success[Try[Any]]({
      case scala.util.Success(_) => true
      case scala.util.Failure(ex) => ex match {
        case _: java.sql.DataTruncation => true
        case _: java.sql.SQLIntegrityConstraintViolationException => true
        case _ => false
      }
    })
```

This worked fine
