### ISSUE TITLE
How to do graceful shutdown?

### ISSUE THREAD

**Issue by kkalavantavanich** [softwaremill/retry#37]
How can I do graceful shutdown using this library? Say I have some code that is doing retry on some HTTP call. Then the application starts shutting down. Can I somehow register that this should be gracefully shut down?

**Comment by adamw** [comment]
I don't think such functionality would fit this library. What you are looking for is probably sth like [`Resource`](https://typelevel.org/cats-effect/datatypes/resource.html) or [`Using`](https://www.scala-lang.org/api/current/scala/util/Using$.html), or `Future.onComplete`

**Comment by kkalavantavanich** [comment]
Do you mean as a wrapper around `retry` or `retry` as a wrapper around those mechanisms?

**Comment by adamw** [comment]
a wrapper around retry. Something like `allocatedResources.flatMap(r => retry(useResource(r)).onComplete(releaseResource(r)))`

**Comment by adamw** [comment]
assuming we're working with `Future`s

**Comment by kkalavantavanich** [comment]
I see. That sounds reasonable. Thanks 🙏 .
